"""access_token_nullable_2

Revision ID: b39c9f61a6b1
Revises: 3d4f9171d258
Create Date: 2024-09-19 18:06:37.966674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39c9f61a6b1'
down_revision: Union[str, None] = '3d4f9171d258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
